// Code generated by "stringer -type ActionType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NUM-1]
	_ = x[IDENT-2]
	_ = x[UNARY-3]
	_ = x[BINARY-4]
}

const _ActionType_name = "NUMIDENTUNARYBINARY"

var _ActionType_index = [...]uint8{0, 3, 8, 13, 19}

func (i ActionType) String() string {
	i -= 1
	if i < 0 || i >= ActionType(len(_ActionType_index)-1) {
		return "ActionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[i]:_ActionType_index[i+1]]
}
