// Code generated by "stringer -type=BuildFlag"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlagNoOps-1]
}

const _BuildFlag_name = "FlagNoOps"

var _BuildFlag_index = [...]uint8{0, 9}

func (i BuildFlag) String() string {
	i -= 1
	if i < 0 || i >= BuildFlag(len(_BuildFlag_index)-1) {
		return "BuildFlag(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BuildFlag_name[_BuildFlag_index[i]:_BuildFlag_index[i+1]]
}
