// Code generated by "stringer -type=NodeType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeNumber-1]
	_ = x[NodeIdent-2]
	_ = x[NodeUnOp-3]
	_ = x[NodeBinOp-4]
}

const _NodeType_name = "NodeNumberNodeIdentNodeUnOpNodeBinOp"

var _NodeType_index = [...]uint8{0, 10, 19, 27, 36}

func (i NodeType) String() string {
	i -= 1
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
