// Code generated by "stringer -type=OpType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mul-1]
	_ = x[FDiv-2]
	_ = x[FMod-3]
	_ = x[IDiv-4]
	_ = x[Add-16]
	_ = x[Sub-17]
	_ = x[MaxP-32]
}

const (
	_OpType_name_0 = "MulFDivFModIDiv"
	_OpType_name_1 = "AddSub"
	_OpType_name_2 = "MaxP"
)

var (
	_OpType_index_0 = [...]uint8{0, 3, 7, 11, 15}
	_OpType_index_1 = [...]uint8{0, 3, 6}
)

func (i OpType) String() string {
	switch {
	case 1 <= i && i <= 4:
		i -= 1
		return _OpType_name_0[_OpType_index_0[i]:_OpType_index_0[i+1]]
	case 16 <= i && i <= 17:
		i -= 16
		return _OpType_name_1[_OpType_index_1[i]:_OpType_index_1[i+1]]
	case i == 32:
		return _OpType_name_2
	default:
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
