// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Eof-0]
	_ = x[Op-1]
	_ = x[ParOpen-2]
	_ = x[ParClose-3]
	_ = x[Number-4]
	_ = x[Ident-5]
}

const _TokenType_name = "EofOpParOpenParCloseNumberIdent"

var _TokenType_index = [...]uint8{0, 3, 5, 12, 20, 26, 31}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
