// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokEof-0]
	_ = x[TokOp-1]
	_ = x[TokParOpen-2]
	_ = x[TokParClose-3]
	_ = x[TokNumber-4]
	_ = x[TokIdent-5]
}

const _TokenType_name = "TokEofTokOpTokParOpenTokParCloseTokNumberTokIdent"

var _TokenType_index = [...]uint8{0, 6, 11, 21, 32, 41, 49}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
