// Code generated by "stringer -type=Unary"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnNegate-1]
}

const _Unary_name = "UnNegate"

var _Unary_index = [...]uint8{0, 8}

func (i Unary) String() string {
	i -= 1
	if i < 0 || i >= Unary(len(_Unary_index)-1) {
		return "Unary(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Unary_name[_Unary_index[i]:_Unary_index[i+1]]
}
